import { Inter } from 'next/font/google'
import './globals.css'

import { ThemeProvider } from "@/components/theme-provider"
import ToastProvider from '@/components/toastProvider'
import Provider from '@/lib/authProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">      
      <body className={inter.className}>
      <Provider>
      <ThemeProvider attribute="class" defaultTheme="system">
        <ToastProvider/>
          {children}
        </ThemeProvider>
      </Provider>
      </body>
    </html>
  )
}
