name: Execute Script on Remote Server

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  execute-remote-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Script on Remote Server
        run: |
          ssh root@195.35.6.155 "cd mymedicos-dashboard && ./run.sh"
